export const FETCH_DISHES_SUCCESSFULLY = 'FETCH_DISHES_SUCCESSFULLY';

export const GET_DISH = 'GET_DISH';
export const SELECTED_ORDER = 'SELECTED_ORDER';
export const GET_ORDER_SUMMARY = 'GET_ORDER_SUMMARY';
export const REMOVE_ORDER_DISH = 'REMOVE_ORDER_DISH';
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const ORDER_DISPATCHED = 'ORDER_DISPATCHED';
